/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backends
         * @description Which predictors are installed, and whether MHCflurry has its weights.
         */
        get: operations["backends_api_backends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reference Info
         * @description Reference proteome state, so the UI can warn before a run rather than after.
         */
        get: operations["reference_info_api_reference_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Default Config */
        get: operations["default_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Weights
         * @description The scored feature weights, which are priors rather than fitted values.
         */
        get: operations["weights_api_weights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/example": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Example Sample
         * @description The bundled example manifest, for the one-click path.
         */
        get: operations["example_sample_api_example_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload
         * @description Stash uploaded inputs in a workspace directory keyed by id.
         */
        post: operations["upload_api_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /**
         * Start Run
         * @description Begin a ranking run and return its id. Poll `/api/runs/{id}` for progress.
         */
        post: operations["start_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run State */
        get: operations["run_state_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Results
         * @description The ranked table, built with the same writer the TSV uses.
         */
        get: operations["results_api_runs__run_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Explain
         * @description Per-feature score decomposition, from `scoring.rank.contributions`.
         */
        get: operations["explain_api_runs__run_id__explain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/download/{artifact}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download
         * @description Serve the files the library's writers already produced.
         */
        get: operations["download_api_runs__run_id__download__artifact__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/benchmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Benchmark
         * @description Score this run against the baselines using an uploaded assay-label TSV.
         *
         *     Labels arrive only here, after the run has finished. Nothing in the ranking
         *     path can see them, which is what makes the comparison worth reading.
         */
        post: operations["benchmark_api_runs__run_id__benchmark_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Features
         * @description Raw feature records, the same payload `features.json` contains.
         */
        get: operations["features_api_runs__run_id__features_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BackendInfo
         * @description Which presentation predictors this deployment can actually use.
         */
        BackendInfo: {
            /** Available */
            available: string[];
            /** Development */
            development: string[];
            /** Default */
            default: string;
            /** Mhcflurry Ready */
            mhcflurry_ready: boolean;
            /** Mhcflurry Detail */
            mhcflurry_detail: string;
        };
        /** BenchmarkReport */
        BenchmarkReport: {
            /** Run Id */
            run_id: string;
            source: components["schemas"]["LabelSource"];
            /** Retrieval */
            retrieval: components["schemas"]["RetrievalSummary"][];
            /** Validation */
            validation: components["schemas"]["ValidationSummary"][];
            /** K */
            k: number;
            /** Positive Ranks */
            positive_ranks: {
                [key: string]: number[];
            };
            /** Pool Size */
            pool_size: number;
        };
        /** Body_benchmark_api_runs__run_id__benchmark_post */
        Body_benchmark_api_runs__run_id__benchmark_post: {
            /** Labels */
            labels: string;
        };
        /** Body_upload_api_uploads_post */
        Body_upload_api_uploads_post: {
            /** Files */
            files: string[];
        };
        /** Contribution */
        Contribution: {
            /** Feature */
            feature: string;
            /** Weight */
            weight: number;
            /** Value */
            value: number;
            /** Contribution */
            contribution: number;
        };
        /**
         * DropReason
         * @enum {string}
         */
        DropReason: "not_pass" | "low_depth" | "low_vaf" | "germline_common" | "subclonal" | "no_expression_data" | "not_expressed" | "allele_not_expressed";
        /**
         * Explanation
         * @description The per-feature decomposition behind one candidate's score.
         */
        Explanation: {
            /** Peptide */
            peptide: string;
            /** Wildtype Peptide */
            wildtype_peptide: string | null;
            /** Allele */
            allele: string;
            /** Gene */
            gene: string;
            /** Hgvsp */
            hgvsp: string;
            /** Score */
            score: number;
            /** Bias */
            bias: number;
            /** Logit */
            logit: number;
            /** Mutation Position */
            mutation_position: number;
            /** Gate Failures */
            gate_failures: string[];
            /** Contributions */
            contributions: components["schemas"]["Contribution"][];
        };
        /** ExpressionConfig */
        ExpressionConfig: {
            /**
             * Min Tpm
             * @default 1
             */
            min_tpm: number;
            /**
             * Min Rna Vaf
             * @default 0.02
             */
            min_rna_vaf: number | null;
            /**
             * Require Rna Evidence
             * @default false
             */
            require_rna_evidence: boolean;
            /** Normal Tpm Ceiling */
            normal_tpm_ceiling?: number | null;
        };
        /** FilterReport */
        FilterReport: {
            /**
             * Kept
             * @default 0
             */
            kept: number;
            /** Dropped */
            dropped?: {
                [key: string]: number;
            };
        };
        /**
         * GateFailure
         * @description Reasons a candidate is excluded outright rather than scored down.
         * @enum {string}
         */
        GateFailure: "weak_binder" | "low_presentation" | "self_peptide" | "normal_tissue_expressed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LabelSource
         * @description Provenance of the loaded labels, shown next to every benchmark number.
         */
        LabelSource: {
            /** Filename */
            filename: string;
            /** Assayed */
            assayed: number;
            /** Positives */
            positives: number;
            /** Negatives */
            negatives: number;
            /** Indeterminate */
            indeterminate: number;
            /** Assays */
            assays: {
                [key: string]: number;
            };
            /** Matched To Run */
            matched_to_run: number;
        };
        /** OutputConfig */
        OutputConfig: {
            /**
             * Top N
             * @default 50
             */
            top_n: number;
            /**
             * Max Per Variant
             * @default 2
             */
            max_per_variant: number;
            /**
             * Include Failed
             * @default false
             */
            include_failed: boolean;
        };
        /** PeptideConfig */
        PeptideConfig: {
            /** Lengths */
            lengths?: number[];
            /**
             * Flank Length
             * @default 10
             */
            flank_length: number;
            /**
             * Drop Self Matching
             * @default true
             */
            drop_self_matching: boolean;
        };
        /** PipelineConfig */
        PipelineConfig: {
            variant_filters?: components["schemas"]["VariantFilterConfig"];
            expression?: components["schemas"]["ExpressionConfig"];
            peptides?: components["schemas"]["PeptideConfig"];
            presentation?: components["schemas"]["PresentationConfig"];
            weights?: components["schemas"]["ScoringWeights"];
            output?: components["schemas"]["OutputConfig"];
        };
        /** PresentationConfig */
        PresentationConfig: {
            /**
             * Backend
             * @default mhcflurry
             */
            backend: string;
            /**
             * Max Affinity Percentile
             * @default 2
             */
            max_affinity_percentile: number;
            /**
             * Min Presentation Score
             * @default 0
             */
            min_presentation_score: number;
            /**
             * Score Wildtype
             * @default true
             */
            score_wildtype: boolean;
        };
        /**
         * ProgressEvent
         * @description One line the pipeline emitted while running.
         */
        ProgressEvent: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Level */
            level: string;
            /** Stage */
            stage: string;
            /** Message */
            message: string;
        };
        /**
         * ReferenceInfo
         * @description State of the reference proteome, which gates two features and a hard gate.
         */
        ReferenceInfo: {
            /** Bundled Stub Path */
            bundled_stub_path: string;
            /** Bundled Stub Proteins */
            bundled_stub_proteins: number;
            /** Cached Release */
            cached_release: string;
            /** Cached Path */
            cached_path?: string | null;
            /** Cached Proteins */
            cached_proteins?: number | null;
            /** Cached Is Stub */
            cached_is_stub?: boolean | null;
            /** Fetch Command */
            fetch_command: string;
        };
        /**
         * ResultsPage
         * @description The ranked table, in exactly the column order the TSV uses.
         */
        ResultsPage: {
            /** Run Id */
            run_id: string;
            /** Sample Id */
            sample_id: string;
            /** Columns */
            columns: string[];
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** Total */
            total: number;
            /** Genes */
            genes: string[];
            /** Alleles */
            alleles: string[];
            /** Gate Failures */
            gate_failures: string[];
        };
        /**
         * RetrievalSummary
         * @description The four numbers a published benchmark is reported on.
         *
         *     Precision and recall are both here because they answer different questions
         *     and diverge sharply when positives are scarce. Precision@10 is what a lab
         *     feels: of ten peptides synthesized, how many worked. Recall@10 is what a
         *     paper asks: of the epitopes that exist, how many did the method surface.
         *     With three positives in a pool, precision@10 cannot exceed 0.3 however
         *     perfect the ranking, so quoting it alone understates a good method.
         */
        RetrievalSummary: {
            /** Method */
            method: string;
            /** Assayed */
            assayed: number;
            /** Positives */
            positives: number;
            /** Recall At 10 */
            recall_at_10: number;
            /** Recall At 20 */
            recall_at_20: number;
            /** Precision At 10 */
            precision_at_10: number;
            /** Hits At 10 */
            hits_at_10: number;
            /** Hits At 20 */
            hits_at_20: number;
            /** Best Positive Rank */
            best_positive_rank: number | null;
        };
        /** RunCreated */
        RunCreated: {
            /** Run Id */
            run_id: string;
        };
        /** RunReport */
        RunReport: {
            /**
             * Variants Read
             * @default 0
             */
            variants_read: number;
            /**
             * Variants Kept
             * @default 0
             */
            variants_kept: number;
            filter_report?: components["schemas"]["FilterReport"];
            /**
             * Peptides Generated
             * @default 0
             */
            peptides_generated: number;
            /** Peptide Errors */
            peptide_errors?: {
                [key: string]: number;
            };
            /**
             * Pairs Scored
             * @default 0
             */
            pairs_scored: number;
            /** Pairs Gated */
            pairs_gated?: {
                [key: string]: number;
            };
            /**
             * Shortlisted
             * @default 0
             */
            shortlisted: number;
            /**
             * Proteome Proteins
             * @default 0
             */
            proteome_proteins: number;
            /**
             * Proteome Is Stub
             * @default false
             */
            proteome_is_stub: boolean;
            /**
             * Expression Available
             * @default false
             */
            expression_available: boolean;
            /**
             * Normal Expression Available
             * @default false
             */
            normal_expression_available: boolean;
        };
        /** RunRequest */
        RunRequest: {
            /**
             * Source
             * @default example
             * @enum {string}
             */
            source: "example" | "upload";
            /** Workspace */
            workspace?: string | null;
            sample?: components["schemas"]["SampleInput"] | null;
            /** Backend */
            backend?: string | null;
            /** Top N */
            top_n?: number | null;
            /**
             * Acknowledge Development Backend
             * @default false
             */
            acknowledge_development_backend: boolean;
        };
        /** RunState */
        RunState: {
            /** Run Id */
            run_id: string;
            status: components["schemas"]["RunStatus"];
            /** Sample Id */
            sample_id?: string | null;
            /** Backend */
            backend?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Events */
            events?: components["schemas"]["ProgressEvent"][];
            report?: components["schemas"]["RunReport"] | null;
            warnings?: components["schemas"]["RunWarnings"];
            config?: components["schemas"]["PipelineConfig"] | null;
            /** Error */
            error?: string | null;
            /** Error Type */
            error_type?: string | null;
            /**
             * Shortlisted
             * @default 0
             */
            shortlisted: number;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "succeeded" | "failed";
        /**
         * RunWarnings
         * @description Caveats that must be visible in any interface, not just the README.
         */
        RunWarnings: {
            /**
             * Proteome Is Stub
             * @default false
             */
            proteome_is_stub: boolean;
            /**
             * Proteome Proteins
             * @default 0
             */
            proteome_proteins: number;
            /** Proteome Detail */
            proteome_detail?: string | null;
            /**
             * Development Backend
             * @default false
             */
            development_backend: boolean;
            /** Development Detail */
            development_detail?: string | null;
            /**
             * Expression Available
             * @default true
             */
            expression_available: boolean;
            /** Expression Detail */
            expression_detail?: string | null;
        };
        /**
         * SampleInput
         * @description Mirrors `data/examples/sample.yaml`.
         *
         *     File fields name a file previously uploaded to a workspace, not a server
         *     path, so a request cannot reach outside its own upload directory.
         */
        SampleInput: {
            /** Sample Id */
            sample_id: string;
            /** Cancer Type */
            cancer_type?: string | null;
            /** Tumor Purity */
            tumor_purity?: number | null;
            /** Hla */
            hla?: string[];
            /** Somatic Vcf */
            somatic_vcf?: string | null;
            /** Variant Tsv */
            variant_tsv?: string | null;
            /** Expression Tsv */
            expression_tsv?: string | null;
            /** Normal Expression Tsv */
            normal_expression_tsv?: string | null;
            /** Tumor Sample Name */
            tumor_sample_name?: string | null;
            /**
             * Proteome
             * @default ensembl
             */
            proteome: string;
        };
        /**
         * ScoringWeights
         * @description Coefficients of a logistic model over normalized features.
         *
         *     Weights are scaled by how well evidenced each feature is, not by how
         *     interesting it sounds. Presentation, clonality and expression are close to
         *     necessary conditions for a T-cell response and carry most of the weight.
         *     The sequence-intrinsic terms are proxies with weak literature support, so
         *     they are kept small on purpose: given them comparable weight and they
         *     dominate the very top of the shortlist, which is the part a lab actually
         *     synthesizes. `tests/test_eval.py` guards against that regression.
         *
         *     Deliberately absent: any "known driver gene" or literature-prominence term.
         *     Driver status is a proxy for publication history, not for T-cell response,
         *     and biases the shortlist toward antigens that are already known to fail.
         *
         *     These are priors. Replace them with `neoantigene refit` output.
         */
        ScoringWeights: {
            /**
             * Bias
             * @default -3
             */
            bias: number;
            /**
             * Presentation
             * @default 2.5
             */
            presentation: number;
            /**
             * Clonality
             * @default 1.5
             */
            clonality: number;
            /**
             * Expression
             * @default 1.2
             */
            expression: number;
            /**
             * Agretopicity
             * @default 0.5
             */
            agretopicity: number;
            /**
             * Tumor Selectivity
             * @default 0.4
             */
            tumor_selectivity: number;
            /**
             * Self Dissimilarity
             * @default 0.25
             */
            self_dissimilarity: number;
            /**
             * Wt Dissimilarity
             * @default 0.15
             */
            wt_dissimilarity: number;
            /**
             * Mutation Exposure
             * @default 0.1
             */
            mutation_exposure: number;
            /**
             * Hydrophobicity
             * @default 0
             */
            hydrophobicity: number;
        };
        /** UploadedFile */
        UploadedFile: {
            /** Name */
            name: string;
            /** Bytes */
            bytes: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationSummary */
        ValidationSummary: {
            /** Method */
            method: string;
            /** K */
            k: number;
            /** Assayed */
            assayed: number;
            /** Positives */
            positives: number;
            /** Hits In Top K */
            hits_in_top_k: number;
            /** Validation Rate */
            validation_rate: number;
            /** Baseline Rate */
            baseline_rate?: number | null;
        };
        /** VariantFilterConfig */
        VariantFilterConfig: {
            /**
             * Require Pass
             * @default true
             */
            require_pass: boolean;
            /**
             * Min Tumor Depth
             * @default 20
             */
            min_tumor_depth: number;
            /**
             * Min Dna Vaf
             * @default 0.05
             */
            min_dna_vaf: number;
            /**
             * Max Population Af
             * @default 0.0001
             */
            max_population_af: number;
            /**
             * Min Ccf
             * @default 0.6
             */
            min_ccf: number;
            /**
             * Tumor Purity
             * @default 0.5
             */
            tumor_purity: number;
        };
        /** Workspace */
        Workspace: {
            /** Id */
            id: string;
            /** Files */
            files: components["schemas"]["UploadedFile"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    backends_api_backends_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackendInfo"];
                };
            };
        };
    };
    reference_info_api_reference_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceInfo"];
                };
            };
        };
    };
    default_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineConfig"];
                };
            };
        };
    };
    weights_api_weights_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    example_sample_api_example_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    upload_api_uploads_post: {
        parameters: {
            query?: {
                workspace?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_api_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunState"][];
                };
            };
        };
    };
    start_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_state_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    results_api_runs__run_id__results_get: {
        parameters: {
            query?: {
                include_gated?: boolean;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_api_runs__run_id__explain_get: {
        parameters: {
            query: {
                peptide: string;
                allele: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Explanation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_api_runs__run_id__download__artifact__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                artifact: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    benchmark_api_runs__run_id__benchmark_post: {
        parameters: {
            query?: {
                k?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_benchmark_api_runs__run_id__benchmark_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    features_api_runs__run_id__features_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
